apiVersion: v1
kind: Pod
metadata:
  name: my-pod
  namespace: default
spec:
  serviceAccountName: metrics-reader
  containers:
    - name: my-container
      image: python:3.9
      command: ["sleep", "3600"]
